http:
  routers:
    edulution-moodle:
      rule: PathPrefix(`/moodle-app`)
      service: edulution-moodle
      entryPoints:
        - websecure
      tls: {}
      priority: 100
      middlewares:
        - moodle-headers

  middlewares:
    moodle-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  services:
    edulution-moodle:
      loadBalancer:
        servers:
          - url: http://edulution-moodle:80
        passHostHeader: true
